id: I4C4E4AAA
legacy_id: P008126
ocr_import_info:
  bdrc_scan_id: W1KG12222
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T02:14:43'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T02:25:17.944204+00:00'
last_modified: 2022-08-27 10:28:33.933948
parser: null
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12222
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12222
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཆོས་ཀྱི་བློ་གྲོས།
  author: མར་པ་ལོ་ཙཱ་བ་ཆོས་ཀྱི་བློ་གྲོས།
statistics:
  ocr_word_mean_confidence_index: 0.8600543916913936
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I1KG12251:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12251
      total_pages: 638
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG12251.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8332836667512727
    legacy_id: v002
  I1KG12250:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12250
      total_pages: 714
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12250.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.857672175895096
    legacy_id: v001
  I1KG12252:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12252
      total_pages: 638
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG12252.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8902423895116334
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
