id: I4C4E4AAA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T02:19:47+00:00'
last_modified: '2022-06-09T04:41:05.385427+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12222
  title: གསུང་འབུམ། ཆོས་ཀྱི་བློ་གྲོས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    222A:
      image_group_id: I1KG12250
      title: Volume 1 of gsung 'bum/_chos kyi blo gros/
      total_pages: 714
      order: 1
      base_file: 222A.txt
    5E1E:
      image_group_id: I1KG12251
      title: Volume 2 of gsung 'bum/_chos kyi blo gros/
      total_pages: 638
      order: 2
      base_file: 5E1E.txt
    DD99:
      image_group_id: I1KG12252
      title: Volume 3 of gsung 'bum/_chos kyi blo gros/
      total_pages: 638
      order: 3
      base_file: DD99.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
