id: P008126
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12222
  title: གསུང་འབུམ། ཆོས་ཀྱི་བློ་གྲོས།
  author: ''
  volumes:
    9e85b12ffd9844e4a55ab0c680be1096:
      image_group_id: I1KG12250
      title: ''
      volume_number: 1
      total_pages: 714
    12e317de590a4c0fbbe17379bbee90b8:
      image_group_id: I1KG12251
      title: ''
      volume_number: 2
      total_pages: 638
    937ce738992d4afe823084deb333450b:
      image_group_id: I1KG12252
      title: ''
      volume_number: 3
      total_pages: 638
ebook_metadata:
  title: གསུང་འབུམ། ཆོས་ཀྱི་བློ་གྲོས།
  author: ''
  sku: P008126
  cover: cover.jpg
  layers:
  - pagination
